import type { Route } from './types';

/** Nine pre-seeded scenic routes covering a variety of world regions. */
export const SEED_ROUTES: Route[] = [
  {
    id: 'seed-1',
    name: 'Pacific Coast Highway',
    region: 'California, USA',
    distance: 123,
    driveTime: '3h 30m',
    roadType: 'Paved',
    curvatureRating: 4,
    highlights: 'Dramatic cliffs, sea-lion rookeries, Bixby Bridge',
    startPoint: 'San Luis Obispo, CA',
    endPoint: 'San Francisco, CA',
    bestSeason: 'Spring / Fall',
    directions: [
      'Head north on CA-1 from San Luis Obispo.',
      'Pass Morro Bay — look for sea otters in the estuary.',
      'Continue through Cambria and San Simeon.',
      'Cross the iconic Bixby Creek Bridge.',
      'Wind through Big Sur cliffs to Carmel-by-the-Sea.',
      'Follow CA-1 north through Monterey to San Francisco.',
    ],
    waypoints: [
      { lat: 35.28, lng: -120.66 },
      { lat: 35.60, lng: -121.19 },
      { lat: 36.00, lng: -121.53 },
      { lat: 36.27, lng: -121.83 },
      { lat: 36.53, lng: -121.92 },
      { lat: 37.78, lng: -122.42 },
    ],
  },
  {
    id: 'seed-2',
    name: 'Blue Ridge Parkway',
    region: 'Appalachians, USA',
    distance: 217,
    driveTime: '5h 00m',
    roadType: 'Paved',
    curvatureRating: 3,
    highlights: 'Fall foliage, Appalachian overlooks, milepost markers',
    startPoint: 'Waynesboro, VA',
    endPoint: 'Cherokee, NC',
    bestSeason: 'Autumn',
    directions: [
      'Begin at Rockfish Gap near Waynesboro, VA.',
      'Drive south along the ridge, stopping at Humpback Rocks.',
      'Continue to the Peaks of Otter for a lake view.',
      'Cross into North Carolina near Cumberland Knob.',
      'Wind through the Linn Cove Viaduct near Grandfather Mountain.',
      'Descend into Cherokee, NC at the southern terminus.',
    ],
    waypoints: [
      { lat: 38.07, lng: -78.88 },
      { lat: 37.77, lng: -79.40 },
      { lat: 37.25, lng: -80.02 },
      { lat: 36.53, lng: -80.84 },
      { lat: 36.05, lng: -81.84 },
      { lat: 35.52, lng: -83.30 },
    ],
  },
  {
    id: 'seed-3',
    name: 'Scottish Highlands — A82',
    region: 'Scotland, UK',
    distance: 108,
    driveTime: '2h 30m',
    roadType: 'Paved',
    curvatureRating: 3,
    highlights: 'Loch Ness, Glencoe valley, Glen Shiel ridgeline',
    startPoint: 'Fort William',
    endPoint: 'Inverness',
    bestSeason: 'Summer',
    directions: [
      'Leave Fort William heading north on the A82.',
      'Drive along the western shore of Loch Lochy.',
      'Pass through the Great Glen beside Loch Oich.',
      'Enter Inverness via Drumnadrochit and the north shore of Loch Ness.',
    ],
    waypoints: [
      { lat: 56.82, lng: -5.11 },
      { lat: 57.00, lng: -4.96 },
      { lat: 57.30, lng: -4.74 },
      { lat: 57.47, lng: -4.23 },
    ],
  },
  {
    id: 'seed-4',
    name: 'Going-to-the-Sun Road',
    region: 'Montana, USA',
    distance: 50,
    driveTime: '2h 00m',
    roadType: 'Paved',
    curvatureRating: 5,
    highlights: 'Logan Pass, glacial cirques, mountain goats',
    startPoint: 'West Glacier, MT',
    endPoint: 'St. Mary, MT',
    bestSeason: 'Summer (mid-Jun to mid-Oct)',
    directions: [
      'Enter Glacier National Park at West Glacier.',
      'Climb through dense cedar forest to Lake McDonald.',
      'Ascend the Garden Wall on the narrow cliffside section.',
      'Summit at Logan Pass (6,646 ft) — check for mountain goats.',
      'Descend the east side through switchbacks to St. Mary Lake.',
    ],
    waypoints: [
      { lat: 48.50, lng: -113.99 },
      { lat: 48.55, lng: -113.84 },
      { lat: 48.58, lng: -113.72 },
      { lat: 48.70, lng: -113.61 },
      { lat: 48.74, lng: -113.43 },
    ],
  },
  {
    id: 'seed-5',
    name: 'Amalfi Coast Drive',
    region: 'Campania, Italy',
    distance: 25,
    driveTime: '1h 30m',
    roadType: 'Paved',
    curvatureRating: 5,
    highlights: 'Clifftop villages, lemon groves, turquoise sea views',
    startPoint: 'Sorrento',
    endPoint: 'Salerno',
    bestSeason: 'May / September',
    directions: [
      'Leave Sorrento on the SS163 heading east.',
      'Hug the cliff above Positano — park and walk down.',
      'Pass through Praiano with its hanging gardens.',
      'Arrive at Amalfi town — stop for granita.',
      'Continue east through Atrani and Maiori to Salerno.',
    ],
    waypoints: [
      { lat: 40.62, lng: 14.37 },
      { lat: 40.63, lng: 14.49 },
      { lat: 40.62, lng: 14.60 },
      { lat: 40.63, lng: 14.60 },
      { lat: 40.61, lng: 14.73 },
      { lat: 40.68, lng: 14.79 },
    ],
  },
  {
    id: 'seed-6',
    name: 'Great Ocean Road',
    region: 'Victoria, Australia',
    distance: 151,
    driveTime: '4h 00m',
    roadType: 'Paved',
    curvatureRating: 3,
    highlights: 'Twelve Apostles, Cape Otway lighthouse, surfing beaches',
    startPoint: 'Torquay, VIC',
    endPoint: 'Allansford, VIC',
    bestSeason: 'Summer (Dec–Feb)',
    directions: [
      'Start at the Great Ocean Road memorial arch in Torquay.',
      'Drive west through Anglesea and Lorne along coastal cliffs.',
      'Detour inland to Cape Otway Lightstation.',
      'Stop at Port Campbell for the Twelve Apostles at sunset.',
      'Continue west to the finish near Allansford.',
    ],
    waypoints: [
      { lat: -38.33, lng: 144.32 },
      { lat: -38.52, lng: 143.93 },
      { lat: -38.85, lng: 143.54 },
      { lat: -38.83, lng: 143.11 },
      { lat: -38.56, lng: 142.56 },
    ],
  },
  {
    id: 'seed-7',
    name: 'Route des Grandes Alpes',
    region: 'Alps, France',
    distance: 468,
    driveTime: '10h 00m',
    roadType: 'Paved',
    curvatureRating: 5,
    highlights: 'Col de l\'Iseran, Mont Blanc views, 16 high passes',
    startPoint: 'Thonon-les-Bains',
    endPoint: 'Nice',
    bestSeason: 'Summer',
    directions: [
      'Leave Thonon-les-Bains on the D902 heading south.',
      'Climb to the Col des Gets (1,164 m).',
      'Descend to Chamonix with Mont Blanc ahead.',
      'Ascend to Col de l\'Iseran (2,770 m) — highest paved pass in France.',
      'Wind down to Briançon, then south through Barcelonnette.',
      'Finish on the Côte d\'Azur in Nice.',
    ],
    waypoints: [
      { lat: 46.37, lng: 6.48 },
      { lat: 45.92, lng: 6.87 },
      { lat: 45.42, lng: 7.02 },
      { lat: 44.90, lng: 6.63 },
      { lat: 44.39, lng: 6.72 },
      { lat: 43.70, lng: 7.27 },
    ],
  },
  {
    id: 'seed-8',
    name: 'Transfăgărășan Highway',
    region: 'Carpathians, Romania',
    distance: 56,
    driveTime: '2h 00m',
    roadType: 'Paved',
    curvatureRating: 5,
    highlights: 'Bâlea Lake, endless hairpins, Fagaras peaks above 2,000 m',
    startPoint: 'Curtea de Argeș',
    endPoint: 'Sibiu',
    bestSeason: 'Summer (Jul–Sep)',
    directions: [
      'Head north from Curtea de Argeș on the DN7C.',
      'Begin the southern ascent with tight hairpin bends.',
      'Pass through the 887 m Transfăgărășan tunnel near the summit.',
      'Stop at Bâlea Lake (2,034 m) for the view.',
      'Descend the long northern hairpins toward Cârțișoara.',
      'Join the A1 motorway south of Sibiu.',
    ],
    waypoints: [
      { lat: 45.11, lng: 24.68 },
      { lat: 45.39, lng: 24.61 },
      { lat: 45.60, lng: 24.62 },
      { lat: 45.70, lng: 24.62 },
      { lat: 45.77, lng: 24.23 },
    ],
  },
  {
    id: 'seed-9',
    name: 'Furka Pass',
    region: 'Swiss Alps, Switzerland',
    distance: 22,
    driveTime: '1h 00m',
    roadType: 'Paved',
    curvatureRating: 4,
    highlights: 'Rhône Glacier, Grimsel Dam, James Bond road',
    startPoint: 'Realp',
    endPoint: 'Gletsch',
    bestSeason: 'Summer (Jun–Oct)',
    directions: [
      'Start in Realp at the foot of the pass.',
      'Ascend tight switchbacks with views of the Urserental.',
      'Reach the summit at 2,429 m — walk to the Rhône Glacier.',
      'Descend north to the junction at Gletsch.',
    ],
    waypoints: [
      { lat: 46.59, lng: 8.51 },
      { lat: 46.57, lng: 8.46 },
      { lat: 46.57, lng: 8.41 },
      { lat: 46.57, lng: 8.35 },
    ],
  },
];
