import { Route } from './types';

/** 9 pre-seeded routes covering a variety of regions and road types. */
export const SEED_ROUTES: Route[] = [
  {
    id: 'pch-1',
    name: 'Pacific Coast Highway',
    region: 'Pacific Coast',
    distance: 123,
    driveTime: '3h 30m',
    curvatureRating: 3,
    roadType: 'Paved',
    highlights: 'Dramatic sea cliffs, Big Sur redwoods, elephant seal beaches',
    waypoints: [
      { lat: 37.86, lng: -122.49 },
      { lat: 37.55, lng: -122.51 },
      { lat: 37.2, lng: -122.41 },
      { lat: 36.6, lng: -121.88 },
      { lat: 36.0, lng: -121.5 },
      { lat: 35.7, lng: -121.3 },
    ],
    startPoint: 'San Francisco, CA',
    endPoint: 'Morro Bay, CA',
    directions: [
      'Head south on CA-1 from San Francisco.',
      "Pass Devil's Slide tunnel — ocean opens up dramatically.",
      'Wind through Half Moon Bay and Santa Cruz coastline.',
      'Enter Big Sur — watch for elephant seals at Piedras Blancas.',
      'Arrive at Morro Bay Rock viewpoint.',
    ],
    bestSeason: 'Spring / Fall',
  },
  {
    id: 'brp-2',
    name: 'Blue Ridge Parkway',
    region: 'Appalachian Mountains',
    distance: 469,
    driveTime: '9h 00m',
    curvatureRating: 4,
    roadType: 'Paved',
    highlights: 'Autumn foliage, mountain overlooks, mile-high ridge vistas',
    waypoints: [
      { lat: 38.88, lng: -78.6 },
      { lat: 38.3, lng: -79.2 },
      { lat: 37.4, lng: -79.9 },
      { lat: 36.6, lng: -80.6 },
      { lat: 35.8, lng: -81.3 },
      { lat: 35.6, lng: -82.5 },
      { lat: 35.5, lng: -83.0 },
    ],
    startPoint: 'Waynesboro, VA (Milepost 0)',
    endPoint: 'Cherokee, NC (Milepost 469)',
    directions: [
      'Begin at Rockfish Gap, Waynesboro and head south.',
      'Stop at Humpback Rocks for a short ridge hike.',
      'Continue past Roanoke Mountain overlook.',
      'Pass through Craggy Gardens near Asheville.',
      'End at Great Smoky Mountains gateway in Cherokee.',
    ],
    bestSeason: 'October (peak foliage)',
  },
  {
    id: 'tod-3',
    name: 'Tail of the Dragon',
    region: 'Smoky Mountains',
    distance: 11,
    driveTime: '0h 45m',
    curvatureRating: 5,
    roadType: 'Paved',
    highlights: '318 curves in 11 miles — a motorcyclist\'s paradise',
    waypoints: [
      { lat: 35.47, lng: -84.07 },
      { lat: 35.46, lng: -84.04 },
      { lat: 35.45, lng: -84.01 },
      { lat: 35.44, lng: -83.99 },
      { lat: 35.45, lng: -83.97 },
    ],
    startPoint: 'Deals Gap, TN (US-129)',
    endPoint: 'Tabcat Bridge, NC',
    directions: [
      'Start at Deals Gap — check your tyre pressure.',
      '318 continuous curves through dense forest.',
      'No intersecting roads for 11 miles — full focus required.',
      'Arrive at Tabcat Bridge; continue on NC-28 or turn around.',
    ],
    bestSeason: 'Spring / Summer',
  },
  {
    id: 'gts-4',
    name: 'Going-to-the-Sun Road',
    region: 'Rocky Mountains',
    distance: 50,
    driveTime: '2h 00m',
    curvatureRating: 4,
    roadType: 'Paved',
    highlights: 'Logan Pass at 6,646 ft, glaciers, mountain goats',
    waypoints: [
      { lat: 48.51, lng: -113.98 },
      { lat: 48.57, lng: -113.82 },
      { lat: 48.64, lng: -113.71 },
      { lat: 48.69, lng: -113.73 },
      { lat: 48.73, lng: -113.81 },
    ],
    startPoint: 'West Glacier, MT',
    endPoint: 'St. Mary, MT',
    directions: [
      'Enter at West Glacier and follow Lake McDonald shore.',
      'Climb the Garden Wall — sheer drop on the driver side.',
      'Cross Logan Pass summit (open July–September only).',
      'Descend through the dramatic St. Mary Lake canyon.',
      'Exit at St. Mary visitor centre.',
    ],
    bestSeason: 'July – September',
  },
  {
    id: 'bth-5',
    name: 'Beartooth Highway',
    region: 'Rocky Mountains',
    distance: 68,
    driveTime: '2h 30m',
    curvatureRating: 5,
    roadType: 'Paved',
    highlights: 'Highest paved road in Wyoming, 28 peaks over 12,000 ft',
    waypoints: [
      { lat: 45.0, lng: -109.45 },
      { lat: 45.04, lng: -109.28 },
      { lat: 45.07, lng: -109.17 },
      { lat: 45.02, lng: -109.05 },
      { lat: 44.98, lng: -109.0 },
    ],
    startPoint: 'Red Lodge, MT',
    endPoint: 'Cooke City, MT (NE Yellowstone)',
    directions: [
      'Leave Red Lodge heading south on US-212.',
      'Switchbacks begin — 5,000 ft elevation gain in 10 miles.',
      'Summit at 10,947 ft with views of 28 mountain peaks.',
      'Descend across the Wyoming plateau.',
      'Arrive at Cooke City, gateway to Yellowstone.',
    ],
    bestSeason: 'June – September',
  },
  {
    id: 'shl-6',
    name: 'A82 Scottish Highlands',
    region: 'Scottish Highlands',
    distance: 100,
    driveTime: '3h 00m',
    curvatureRating: 3,
    roadType: 'Paved',
    highlights: 'Loch Lomond shores, Glencoe valley, moorland grandeur',
    waypoints: [
      { lat: 56.0, lng: -4.6 },
      { lat: 56.38, lng: -4.62 },
      { lat: 56.68, lng: -4.79 },
      { lat: 56.83, lng: -5.0 },
      { lat: 56.97, lng: -5.17 },
    ],
    startPoint: 'Balloch, Loch Lomond',
    endPoint: 'Fort William',
    directions: [
      "Head north from Balloch along Loch Lomond's west shore.",
      'Continue through Crianlarich — mountains close in.',
      "Drop into Glencoe — stop at the Three Sisters viewpoint.",
      'Pass through Ballachulish and the Loch Linnhe shore.',
      'Arrive at Fort William with Ben Nevis in view.',
    ],
    bestSeason: 'May – September',
  },
  {
    id: 'aml-7',
    name: 'Amalfi Coast Drive',
    region: 'Southern Italy',
    distance: 34,
    driveTime: '1h 30m',
    curvatureRating: 5,
    roadType: 'Paved',
    highlights: 'Pastel villages, sea cliffs, hairpin bends, lemon groves',
    waypoints: [
      { lat: 40.62, lng: 14.48 },
      { lat: 40.63, lng: 14.58 },
      { lat: 40.63, lng: 14.6 },
      { lat: 40.65, lng: 14.61 },
      { lat: 40.66, lng: 14.63 },
    ],
    startPoint: 'Sorrento',
    endPoint: 'Salerno',
    directions: [
      'Depart Sorrento on SS163 heading east.',
      'Wind through Positano — colourful buildings cling to the cliffs.',
      "Navigate Amalfi's hairpin descent into the town centre.",
      'Continue through Ravello turnoff and Minori.',
      'Arrive at Salerno with Tyrrhenian Sea views.',
    ],
    bestSeason: 'April – June / September – October',
  },
  {
    id: 'trl-8',
    name: 'Trollstigen, Norway',
    region: 'Norwegian Fjords',
    distance: 8,
    driveTime: '0h 30m',
    curvatureRating: 5,
    roadType: 'Paved',
    highlights: '11 hairpin bends, 850 m ascent, Stigfossen waterfall',
    waypoints: [
      { lat: 62.455, lng: 7.675 },
      { lat: 62.457, lng: 7.663 },
      { lat: 62.46, lng: 7.655 },
      { lat: 62.464, lng: 7.648 },
      { lat: 62.468, lng: 7.652 },
    ],
    startPoint: 'Valldal valley base',
    endPoint: 'Trollstigen Visitor Centre (summit)',
    directions: [
      'Begin at the base in the Valldal valley.',
      'Switchbacks 1–5: the waterfall roars to your right.',
      'Switchbacks 6–11: road narrows — caravans prohibited.',
      'Arrive at the summit visitor centre for panoramic fjord views.',
    ],
    bestSeason: 'June – September',
  },
  {
    id: 'rga-9',
    name: 'Route des Grandes Alpes',
    region: 'French Alps',
    distance: 74,
    driveTime: '3h 00m',
    curvatureRating: 4,
    roadType: 'Paved',
    highlights: "Col de l'Iseran (2,770 m), glacial scenery, alpine meadows",
    waypoints: [
      { lat: 45.7, lng: 6.87 },
      { lat: 45.58, lng: 6.98 },
      { lat: 45.43, lng: 7.03 },
      { lat: 45.3, lng: 7.04 },
      { lat: 45.19, lng: 6.97 },
    ],
    startPoint: 'Bourg-Saint-Maurice, France',
    endPoint: 'Lanslebourg-Mont-Cenis, France',
    directions: [
      "Leave Bourg-Saint-Maurice southbound toward Val d'Isère.",
      'Climb D902 through ski resort villages.',
      "Summit Col de l'Iseran — highest paved col in the Alps.",
      'Descend through Bonneval-sur-Arc.',
      'Arrive at Lanslebourg at the Italian border.',
    ],
    bestSeason: 'June – September',
  },
];
